In [1]:
import pandas as pd
from dateutil import parser

In [2]:
# import datasets
raw_data = pd.read_csv("raw_dataset.csv", parse_dates=["date"])
weather_data = pd.read_csv("weather_1995_2018.csv")

In [4]:
raw_data.head()

,location_id,location_name,date,direction,vehicle_type,hour_1,hour_2,hour_3,hour_4,hour_5,...,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,hour_24
0,168,Askisto,2013-12-01,1,11 HA-PA,123.0,124.0,80.0,71.0,123.0,...,1288.0,1271.0,1210.0,1143.0,880.0,670.0,471.0,292.0,222.0,94.0
1,168,Askisto,2013-12-01,1,12 KAIP,2.0,1.0,1.0,1.0,0.0,...,13.0,12.0,13.0,8.0,5.0,8.0,3.0,5.0,1.0,8.0
2,168,Askisto,2013-12-01,1,13 Linja-autot,1.0,2.0,1.0,1.0,0.0,...,4.0,2.0,1.0,2.0,2.0,2.0,1.0,3.0,2.0,1.0
3,168,Askisto,2013-12-01,1,14 KAPP,0.0,0.0,0.0,0.0,1.0,...,9.0,2.0,3.0,4.0,3.0,8.0,16.0,12.0,19.0,6.0
4,168,Askisto,2013-12-01,1,15 KATP,0.0,0.0,0.0,0.0,1.0,...,6.0,12.0,3.0,8.0,5.0,6.0,7.0,9.0,12.0,7.0

In [18]:
rows = raw_data[(raw_data.date == "2013-12-01") & (raw_data.location_id == 168)]

In [19]:
rows

,location_id,location_name,date,direction,vehicle_type,hour_1,hour_2,hour_3,hour_4,hour_5,...,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,hour_24
0,168,Askisto,2013-12-01,1,11 HA-PA,123.0,124.0,80.0,71.0,123.0,...,1288.0,1271.0,1210.0,1143.0,880.0,670.0,471.0,292.0,222.0,94.0
1,168,Askisto,2013-12-01,1,12 KAIP,2.0,1.0,1.0,1.0,0.0,...,13.0,12.0,13.0,8.0,5.0,8.0,3.0,5.0,1.0,8.0
2,168,Askisto,2013-12-01,1,13 Linja-autot,1.0,2.0,1.0,1.0,0.0,...,4.0,2.0,1.0,2.0,2.0,2.0,1.0,3.0,2.0,1.0
3,168,Askisto,2013-12-01,1,14 KAPP,0.0,0.0,0.0,0.0,1.0,...,9.0,2.0,3.0,4.0,3.0,8.0,16.0,12.0,19.0,6.0
4,168,Askisto,2013-12-01,1,15 KATP,0.0,0.0,0.0,0.0,1.0,...,6.0,12.0,3.0,8.0,5.0,6.0,7.0,9.0,12.0,7.0
5,168,Askisto,2013-12-01,1,16 HA + PK,0.0,1.0,0.0,0.0,0.0,...,28.0,15.0,25.0,22.0,9.0,7.0,3.0,3.0,1.0,1.0
6,168,Askisto,2013-12-01,1,17 HA + AV,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,3.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
7,168,Askisto,2013-12-01,2,11 HA-PA,198.0,114.0,91.0,95.0,61.0,...,1201.0,1275.0,1265.0,1150.0,1059.0,786.0,664.0,388.0,212.0,211.0
8,168,Askisto,2013-12-01,2,12 KAIP,5.0,5.0,0.0,1.0,0.0,...,8.0,8.0,3.0,6.0,4.0,7.0,4.0,9.0,3.0,2.0
9,168,Askisto,2013-12-01,2,13 Linja-autot,3.0,2.0,1.0,1.0,0.0,...,3.0,1.0,1.0,2.0,2.0,1.0,2.0,4.0,3.0,2.0
10,168,Askisto,2013-12-01,2,14 KAPP,0.0,0.0,0.0,2.0,1.0,...,10.0,14.0,18.0,4.0,9.0,8.0,10.0,4.0,2.0,2.0
11,168,Askisto,2013-12-01,2,15 KATP,2.0,0.0,0.0,0.0,0.0,...,2.0,2.0,6.0,4.0,13.0,7.0,7.0,8.0,3.0,5.0
12,168,Askisto,2013-12-01,2,16 HA + PK,1.0,4.0,0.0,0.0,1.0,...,17.0,10.0,17.0,11.0,11.0,6.0,3.0,3.0,1.0,0.0
13,168,Askisto,2013-12-01,2,17 HA + AV,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0